spring:
  datasource:
    username: root
    password: 390470265
    url: jdbc:mysql:///openapi-admin?userUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
mybatis:
  type-aliases-package: com.itqf.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
